"""create core intelligence model

Revision ID: 6a4cae0a31d9
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6a4cae0a31d9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

intelligence_type = postgresql.ENUM(
    "observed", "assessed", name="intelligence_type", create_type=False
)
intelligence_origin = postgresql.ENUM(
    "imported", "watchtower", name="intelligence_origin", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    intelligence_type.create(bind, checkfirst=True)
    intelligence_origin.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(canonical_name) <> ''", name=op.f("ck_actors_canonical_name_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''", name=op.f("ck_actors_normalized_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actors")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_actors_normalized_name")),
    )
    op.create_table(
        "behaviors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_behaviors_name_not_blank")),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''", name=op.f("ck_behaviors_normalized_name_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_behaviors")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_behaviors_normalized_name")),
    )
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(kind) <> ''", name=op.f("ck_sources_kind_not_blank")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_sources_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_sources_name")),
    )
    op.create_table(
        "aliases",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("source_native_id", sa.String(length=512), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_aliases_name_not_blank")),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''", name=op.f("ck_aliases_normalized_name_not_blank")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_aliases_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
            name=op.f("fk_aliases_actor_id_actors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_aliases_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aliases")),
        sa.UniqueConstraint("source_id", "normalized_name", name=op.f("uq_aliases_source_id")),
    )
    op.create_index(op.f("ix_aliases_actor_id"), "aliases", ["actor_id"], unique=False)
    op.create_index("ix_aliases_normalized_name", "aliases", ["normalized_name"], unique=False)
    op.create_index(op.f("ix_aliases_source_id"), "aliases", ["source_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_native_id", sa.String(length=512), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("intelligence_type", intelligence_type, nullable=False),
        sa.Column("origin", intelligence_origin, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_campaigns_name_not_blank")),
        sa.CheckConstraint(
            "btrim(normalized_name) <> ''", name=op.f("ck_campaigns_normalized_name_not_blank")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_campaigns_confidence_range"),
        ),
        sa.CheckConstraint(
            "first_seen IS NULL OR last_seen IS NULL OR first_seen <= last_seen",
            name=op.f("ck_campaigns_time_range_order"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_campaigns_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("source_id", "normalized_name", name=op.f("uq_campaigns_source_id")),
    )
    op.create_index("ix_campaigns_first_seen", "campaigns", ["first_seen"], unique=False)
    op.create_index("ix_campaigns_last_seen", "campaigns", ["last_seen"], unique=False)
    op.create_index(op.f("ix_campaigns_source_id"), "campaigns", ["source_id"], unique=False)
    op.create_table(
        "raw_evidence",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("source_native_id", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(storage_uri) <> ''", name=op.f("ck_raw_evidence_storage_uri_not_blank")
        ),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_raw_evidence_sha256_lower_hex")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_evidence_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_evidence")),
        sa.UniqueConstraint("source_id", "content_sha256", name=op.f("uq_raw_evidence_source_id")),
    )
    op.create_index(
        "ix_raw_evidence_content_sha256", "raw_evidence", ["content_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_raw_evidence_published_at"), "raw_evidence", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_raw_evidence_source_id"), "raw_evidence", ["source_id"], unique=False)
    op.create_index("ix_raw_evidence_storage_uri", "raw_evidence", ["storage_uri"], unique=False)
    op.create_table(
        "techniques",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(external_id) <> ''", name=op.f("ck_techniques_external_id_not_blank")
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_techniques_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_techniques_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_techniques")),
        sa.UniqueConstraint("source_id", "external_id", name=op.f("uq_techniques_source_id")),
    )
    op.create_index(op.f("ix_techniques_external_id"), "techniques", ["external_id"], unique=False)
    op.create_index(op.f("ix_techniques_source_id"), "techniques", ["source_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("raw_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("citation", sa.String(length=500), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("locator", sa.String(length=1000), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("origin", intelligence_origin, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(citation) <> ''", name=op.f("ck_evidence_citation_not_blank")),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_evidence_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_evidence_id"],
            ["raw_evidence.id"],
            name=op.f("fk_evidence_raw_evidence_id_raw_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_evidence_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_index(op.f("ix_evidence_captured_at"), "evidence", ["captured_at"], unique=False)
    op.create_index(
        op.f("ix_evidence_raw_evidence_id"), "evidence", ["raw_evidence_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_source_id"), "evidence", ["source_id"], unique=False)
    op.create_table(
        "observations",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("raw_evidence_id", sa.Uuid(), nullable=True),
        sa.Column("source_native_id", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("intelligence_type", intelligence_type, nullable=False),
        sa.Column("origin", intelligence_origin, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(summary) <> ''", name=op.f("ck_observations_summary_not_blank")),
        sa.CheckConstraint("btrim(title) <> ''", name=op.f("ck_observations_title_not_blank")),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_observations_confidence_range"),
        ),
        sa.CheckConstraint(
            "first_seen IS NULL OR last_seen IS NULL OR first_seen <= last_seen",
            name=op.f("ck_observations_time_range_order"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_evidence_id"],
            ["raw_evidence.id"],
            name=op.f("fk_observations_raw_evidence_id_raw_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_observations_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint(
            "source_id", "source_native_id", name=op.f("uq_observations_source_id")
        ),
    )
    op.create_index("ix_observations_first_seen", "observations", ["first_seen"], unique=False)
    op.create_index("ix_observations_last_seen", "observations", ["last_seen"], unique=False)
    op.create_index("ix_observations_observed_at", "observations", ["observed_at"], unique=False)
    op.create_index(
        op.f("ix_observations_raw_evidence_id"), "observations", ["raw_evidence_id"], unique=False
    )
    op.create_index(op.f("ix_observations_source_id"), "observations", ["source_id"], unique=False)
    op.create_table(
        "actor_observations",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
            name=op.f("fk_actor_observations_actor_id_actors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_actor_observations_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("actor_id", "observation_id", name=op.f("pk_actor_observations")),
    )
    op.create_table(
        "observation_behaviors",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("behavior_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["behavior_id"],
            ["behaviors.id"],
            name=op.f("fk_observation_behaviors_behavior_id_behaviors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_behaviors_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "observation_id", "behavior_id", name=op.f("pk_observation_behaviors")
        ),
    )
    op.create_table(
        "observation_evidence",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_observation_evidence_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_evidence_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "observation_id", "evidence_id", name=op.f("pk_observation_evidence")
        ),
    )
    op.create_table(
        "observation_techniques",
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("technique_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_techniques_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["technique_id"],
            ["techniques.id"],
            name=op.f("fk_observation_techniques_technique_id_techniques"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "observation_id", "technique_id", name=op.f("pk_observation_techniques")
        ),
    )
    op.create_table(
        "relationships",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column("relationship_type", sa.String(length=100), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("intelligence_type", intelligence_type, nullable=False),
        sa.Column("origin", intelligence_origin, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(relationship_type) <> ''", name=op.f("ck_relationships_type_not_blank")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_relationships_confidence_range"),
        ),
        sa.CheckConstraint(
            "first_seen IS NULL OR last_seen IS NULL OR first_seen <= last_seen",
            name=op.f("ck_relationships_time_range_order"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["actors.id"],
            name=op.f("fk_relationships_actor_id_actors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_relationships_campaign_id_campaigns"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_relationships_evidence_id_evidence"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_relationships_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationships")),
        sa.UniqueConstraint(
            "actor_id",
            "relationship_type",
            "campaign_id",
            "source_id",
            name=op.f("uq_relationships_actor_id"),
        ),
    )
    op.create_index(op.f("ix_relationships_actor_id"), "relationships", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_relationships_campaign_id"), "relationships", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_evidence_id"), "relationships", ["evidence_id"], unique=False
    )
    op.create_index("ix_relationships_first_seen", "relationships", ["first_seen"], unique=False)
    op.create_index("ix_relationships_last_seen", "relationships", ["last_seen"], unique=False)
    op.create_index(
        op.f("ix_relationships_source_id"), "relationships", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relationships_source_id"), table_name="relationships")
    op.drop_index("ix_relationships_last_seen", table_name="relationships")
    op.drop_index("ix_relationships_first_seen", table_name="relationships")
    op.drop_index(op.f("ix_relationships_evidence_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_campaign_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_actor_id"), table_name="relationships")
    op.drop_table("relationships")
    op.drop_table("observation_techniques")
    op.drop_table("observation_evidence")
    op.drop_table("observation_behaviors")
    op.drop_table("actor_observations")
    op.drop_index(op.f("ix_observations_source_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_raw_evidence_id"), table_name="observations")
    op.drop_index("ix_observations_observed_at", table_name="observations")
    op.drop_index("ix_observations_last_seen", table_name="observations")
    op.drop_index("ix_observations_first_seen", table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_evidence_source_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_raw_evidence_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_captured_at"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_techniques_source_id"), table_name="techniques")
    op.drop_index(op.f("ix_techniques_external_id"), table_name="techniques")
    op.drop_table("techniques")
    op.drop_index("ix_raw_evidence_storage_uri", table_name="raw_evidence")
    op.drop_index(op.f("ix_raw_evidence_source_id"), table_name="raw_evidence")
    op.drop_index(op.f("ix_raw_evidence_published_at"), table_name="raw_evidence")
    op.drop_index("ix_raw_evidence_content_sha256", table_name="raw_evidence")
    op.drop_table("raw_evidence")
    op.drop_index(op.f("ix_campaigns_source_id"), table_name="campaigns")
    op.drop_index("ix_campaigns_last_seen", table_name="campaigns")
    op.drop_index("ix_campaigns_first_seen", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_aliases_source_id"), table_name="aliases")
    op.drop_index("ix_aliases_normalized_name", table_name="aliases")
    op.drop_index(op.f("ix_aliases_actor_id"), table_name="aliases")
    op.drop_table("aliases")
    op.drop_table("sources")
    op.drop_table("behaviors")
    op.drop_table("actors")
    bind = op.get_bind()
    intelligence_origin.drop(bind, checkfirst=True)
    intelligence_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
