"""add raw evidence intake metadata

Revision ID: 83c89c27e40c
Revises: 6a4cae0a31d9
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "83c89c27e40c"
down_revision: str | Sequence[str] | None = "6a4cae0a31d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

retrieval_status = postgresql.ENUM(
    "succeeded", "failed", name="retrieval_status", create_type=False
)
processing_state = postgresql.ENUM(
    "pending", "processing", "succeeded", "failed", name="processing_state", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    retrieval_status.create(bind, checkfirst=True)
    processing_state.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raw_evidence", sa.Column("storage_key", sa.String(length=1024), nullable=True))
    op.add_column("raw_evidence", sa.Column("source_locator", sa.Text(), nullable=True))
    op.add_column(
        "raw_evidence", sa.Column("original_filename", sa.String(length=255), nullable=True)
    )
    op.add_column("raw_evidence", sa.Column("content_size_bytes", sa.BigInteger(), nullable=True))
    op.add_column(
        "raw_evidence",
        sa.Column(
            "retrieval_status",
            retrieval_status,
            server_default=sa.text("'succeeded'"),
            nullable=False,
        ),
    )
    op.add_column(
        "raw_evidence",
        sa.Column(
            "processing_state",
            processing_state,
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
    )
    op.add_column("raw_evidence", sa.Column("processing_error", sa.Text(), nullable=True))
    op.add_column(
        "raw_evidence",
        sa.Column("processing_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "raw_evidence", sa.Column("last_processed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "ix_raw_evidence_processing_state", "raw_evidence", ["processing_state"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_raw_evidence_storage_key"), "raw_evidence", ["storage_key"]
    )
    op.add_column("sources", sa.Column("policy_notes", sa.Text(), nullable=True))
    op.add_column("sources", sa.Column("license_name", sa.String(length=255), nullable=True))
    op.add_column("sources", sa.Column("license_url", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_raw_evidence_source_locator_not_blank"),
        "raw_evidence",
        "source_locator IS NULL OR btrim(source_locator) <> ''",
    )
    op.create_check_constraint(
        op.f("ck_raw_evidence_storage_key_not_blank"),
        "raw_evidence",
        "storage_key IS NULL OR btrim(storage_key) <> ''",
    )
    op.create_check_constraint(
        op.f("ck_raw_evidence_original_filename_not_blank"),
        "raw_evidence",
        "original_filename IS NULL OR btrim(original_filename) <> ''",
    )
    op.create_check_constraint(
        op.f("ck_raw_evidence_content_size_positive"),
        "raw_evidence",
        "content_size_bytes IS NULL OR content_size_bytes > 0",
    )
    op.create_check_constraint(
        op.f("ck_raw_evidence_processing_attempts_nonnegative"),
        "raw_evidence",
        "processing_attempts >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_raw_evidence_processing_attempts_nonnegative"),
        "raw_evidence",
        type_="check",
    )
    op.drop_constraint(op.f("ck_raw_evidence_content_size_positive"), "raw_evidence", type_="check")
    op.drop_constraint(
        op.f("ck_raw_evidence_original_filename_not_blank"), "raw_evidence", type_="check"
    )
    op.drop_constraint(op.f("ck_raw_evidence_storage_key_not_blank"), "raw_evidence", type_="check")
    op.drop_constraint(
        op.f("ck_raw_evidence_source_locator_not_blank"), "raw_evidence", type_="check"
    )
    op.drop_column("sources", "license_url")
    op.drop_column("sources", "license_name")
    op.drop_column("sources", "policy_notes")
    op.drop_constraint(op.f("uq_raw_evidence_storage_key"), "raw_evidence", type_="unique")
    op.drop_index("ix_raw_evidence_processing_state", table_name="raw_evidence")
    op.drop_column("raw_evidence", "last_processed_at")
    op.drop_column("raw_evidence", "processing_attempts")
    op.drop_column("raw_evidence", "processing_error")
    op.drop_column("raw_evidence", "processing_state")
    op.drop_column("raw_evidence", "retrieval_status")
    op.drop_column("raw_evidence", "content_size_bytes")
    op.drop_column("raw_evidence", "original_filename")
    op.drop_column("raw_evidence", "source_locator")
    op.drop_column("raw_evidence", "storage_key")
    bind = op.get_bind()
    processing_state.drop(bind, checkfirst=True)
    retrieval_status.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
